# Generated by Django 3.2.8 on 2021-11-04 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PL', 'text/plain'), ('MD', 'text/markdown')], max_length=2)),
                ('comment', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source', models.URLField(max_length=2048)),
                ('origin', models.URLField(max_length=2048)),
                ('description', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=4)),
                ('content_text', models.TextField(max_length=200)),
                ('content_media', models.BinaryField(blank=True, max_length=1000, null=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('PB', 'PUBLIC'), ('FRD', 'FRIENDS'), ('PR', 'PRIVATE')], default='PB', max_length=10)),
                ('unlisted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialDistribution.author')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('displayName', models.CharField(max_length=50)),
                ('githubUrl', models.CharField(max_length=50, null=True)),
                ('profileImageUrl', models.CharField(max_length=50, null=True)),
                ('followers', models.ManyToManyField(blank=True, to='socialDistribution.LocalAuthor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('socialDistribution.author',),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDistribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDistribution.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialDistribution.localauthor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.localauthor'),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socialDistribution.localauthor')),
                ('follow_requests', models.ManyToManyField(blank=True, related_name='follow_requests', to='socialDistribution.LocalAuthor')),
                ('posts', models.ManyToManyField(blank=True, related_name='pushed_posts', to='socialDistribution.Post')),
            ],
        ),
    ]
