# Generated by Django 3.2.8 on 2021-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('PL', 'text/plain'), ('MD', 'text/markdown')], default='PL', max_length=255),
        ),
    ]
