# Generated by Django 3.2.8 on 2021-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpost',
            name='origin',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='localpost',
            name='source',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='origin',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='source',
            field=models.URLField(default='', max_length=2048),
        ),
    ]
