# Generated by Django 3.2.8 on 2021-11-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
