# Generated by Django 3.2.8 on 2021-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_auto_20211123_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localauthor',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='localauthor',
            name='githubUrl',
        ),
        migrations.RemoveField(
            model_name='localauthor',
            name='profileImageUrl',
        ),
        migrations.AddField(
            model_name='author',
            name='_always_up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='Anonymous User', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='githubUrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImageUrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='content_type',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=50),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='content_type',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=50),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=50),
        ),
    ]
