# Generated by Django 3.2.8 on 2021-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_auto_20211106_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(related_name='posts', to='socialDistribution.Post'),
        ),
    ]
