# Generated by Django 3.2.8 on 2021-11-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_auto_20211129_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='Anonymous User', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='githubUrl',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImageUrl',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='content_type',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=255),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='public_id',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=255),
        ),
        migrations.AlterField(
            model_name='localauthor',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='content_type',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=255),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='public_id',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=255),
        ),
    ]
