# Generated by Django 3.2.8 on 2021-11-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_auto_20211106_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='localauthor',
            name='follow_requests',
            field=models.ManyToManyField(related_name='follow_requests_reverse', to='socialDistribution.LocalAuthor'),
        ),
        migrations.AddField(
            model_name='localauthor',
            name='inbox_posts',
            field=models.ManyToManyField(to='socialDistribution.Post'),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
