# Generated by Django 3.2.8 on 2021-11-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_author_profileimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', to='socialDistribution.Author'),
        ),
    ]
