# Generated by Django 3.2.8 on 2021-11-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_auto_20211107_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='LocalPost',
        ),
    ]
