# Generated by Django 3.2.8 on 2021-12-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_auto_20211129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='follow',
            name='_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='socialDistribution.author'),
        ),
    ]
