# Generated by Django 3.2.8 on 2021-11-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
