# Generated by Django 3.2.8 on 2021-11-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_auto_20211111_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxpost',
            name='count',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='count',
        ),
        migrations.AddField(
            model_name='inboxpost',
            name='_author_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboxpost',
            name='categories',
            field=models.CharField(default=[], max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localpost',
            name='categories',
            field=models.CharField(default=[], max_length=2000),
            preserve_default=False,
        ),
    ]
