# Generated by Django 3.2.8 on 2021-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_auto_20211129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='_is_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
