# Generated by Django 3.2.8 on 2021-11-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_auto_20211109_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(to='socialDistribution.Post'),
        ),
    ]
