# Generated by Django 3.2.8 on 2021-11-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='githubUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImageUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
