# Generated by Django 3.2.8 on 2021-12-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0004_auto_20211201_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='socialDistribution.author'),
        ),
    ]
