# Generated by Django 3.2.8 on 2021-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0004_rename_post_localpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('public_id', models.URLField()),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2000)),
                ('categories', models.CharField(max_length=2000)),
                ('author', models.URLField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField()),
            ],
        ),
    ]
