# Generated by Django 3.2.8 on 2021-11-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImageUrl',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
