# Generated by Django 3.2.8 on 2021-11-17 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0004_auto_20211109_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('public_id', models.URLField()),
                ('description', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=4)),
                ('content', models.CharField(blank=True, max_length=4096, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('source', models.URLField(max_length=2048)),
                ('origin', models.URLField(max_length=2048)),
                ('author', models.URLField(max_length=2048)),
                ('_author_json', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('public_id', models.URLField()),
                ('description', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=4)),
                ('content', models.CharField(blank=True, max_length=4096, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('content_media', models.BinaryField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='localauthor',
            name='follow_requests',
            field=models.ManyToManyField(related_name='follow_requests_reverse', to='socialDistribution.LocalAuthor'),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.AddField(
            model_name='localpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialDistribution.localauthor'),
        ),
        migrations.AddField(
            model_name='localpost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='socialDistribution.Category'),
        ),
        migrations.AddField(
            model_name='inboxpost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='socialDistribution.Category'),
        ),
        migrations.AddField(
            model_name='localauthor',
            name='inbox_posts',
            field=models.ManyToManyField(to='socialDistribution.InboxPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.localpost'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDistribution.localpost'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
