# Generated by Django 3.2.8 on 2021-11-09 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0005_inboxpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxpost',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='content_media',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='localpost',
            name='source',
        ),
        migrations.AddField(
            model_name='localpost',
            name='content',
            field=models.BinaryField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='localpost',
            name='public_id',
            field=models.URLField(default='http://12.0.0.1:800/author/blah/posts/blahh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='author',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='content',
            field=models.BinaryField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='content_type',
            field=models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=4),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='origin',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='source',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FRD', 'FRIENDS'), ('PR', 'PRIVATE')], default='PB', max_length=10),
        ),
    ]
