# Generated by Django 3.2.8 on 2021-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0006_auto_20211108_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxpost',
            name='content',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='content',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
