# Generated by Django 3.2.8 on 2021-11-09 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0007_auto_20211108_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpost',
            name='content_media',
            field=models.BinaryField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inboxpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=10),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='localpost',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('FR', 'FRIEND'), ('PR', 'PRIVATE')], default='PB', max_length=10),
        ),
    ]
