# Generated by Django 3.2.8 on 2021-11-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0008_auto_20211108_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthor',
            name='inbox_posts',
            field=models.ManyToManyField(to='socialDistribution.InboxPost'),
        ),
    ]
