# Generated by Django 3.2.8 on 2021-11-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_prefix',
            field=models.CharField(blank=True, default='/api', max_length=200),
        ),
    ]
