# Generated by Django 3.2.8 on 2021-11-29 16:32

from django.db import migrations
import secrets
from cmput404.constants import HOST


def add_local_auth_credentials(apps, schema_editor):
    Node = apps.get_model('api', 'Node')

    # Add credentials for host server
    local_secret = secrets.token_hex(10)
    Node.objects.get_or_create(
        host=HOST,
        api_prefix="/api",
        username="local",
        password=local_secret,
        remote_credentials=False
    )
    Node.objects.get_or_create(
        host=HOST,
        api_prefix="/api",
        username="local",
        password=local_secret,
        remote_credentials=True
    )


def add_dev_dummy_auth_credentials(apps, schema_editor):
    Node = apps.get_model('api', 'Node')

    # Add local dummy server (if running locally)
    if "127.0.0.1" in HOST:
        dummy_host = "127.0.0.1:8080" if ":8000" in HOST else "127.0.0.1:8000"

        Node.objects.get_or_create(
            host=dummy_host,
            api_prefix="/api",
            username="dummy",
            password="secret",
            remote_credentials=False
        )
        Node.objects.get_or_create(
            host=dummy_host,
            api_prefix="/api",
            username="dummy",
            password="secret",
            remote_credentials=True
        )


def add_prod_auth_credentials(apps, schema_editor):
    Node = apps.get_model('api', 'Node')

    # Add remote group credentials if running in prod
    if HOST == "social-distribution-fall2021.herokuapp.com":

        # Add inbound credentials
        # Clone Team 04
        Node.objects.get_or_create(
            host="cmput404f21-team04.herokuapp.com",
            api_prefix="/api",
            username="team04clone",
            password="secret04clone",
            remote_credentials=False
        )
        # Team 08
        Node.objects.get_or_create(
            host="cmput404-bettersocial.herokuapp.com",
            api_prefix="/api",
            username="team08",
            password="secret08",
            remote_credentials=False
        )
        # Team 11
        Node.objects.get_or_create(
            host="cmput404fall21g11.herokuapp.com",
            api_prefix="/api",
            username="team11",
            password="secret11",
            remote_credentials=False
        )
        # Team 16
        Node.objects.get_or_create(
            host="i-connect.herokuapp.com",
            api_prefix="/service",
            username="team16",
            password="secret16",
            remote_credentials=False
        )

        # Add outbound credentials
        # Clone Team 04
        Node.objects.get_or_create(
            host="cmput404f21-team04.herokuapp.com",
            api_prefix="/api",
            username="theOG",
            password="secretOG",
            remote_credentials=True
        )
        # Team 08
        Node.objects.get_or_create(
            host="cmput404-bettersocial.herokuapp.com",
            api_prefix="/api",
            username="team4",
            password="team4",
            remote_credentials=True
        )
        # Team 11
        Node.objects.get_or_create(
            host="cmput404fall21g11.herokuapp.com",
            api_prefix="/api",
            username="team4",
            password="123456",
            remote_credentials=True
        )
        # Team 16
        Node.objects.get_or_create(
            host="i-connect.herokuapp.com",
            api_prefix="/service",
            username="admin",
            password="admin",
            remote_credentials=True
        )


def add_prod_clone_auth_credentials(apps, schema_editor):
    Node = apps.get_model('api', 'Node')

    # Add credentials if deployed on clone
    if HOST == "cmput404f21-team04.herokuapp.com":
        Node.objects.get_or_create(
            host="social-distribution-fall2021.herokuapp.com",
            api_prefix="/api",
            username="theOG",
            password="secretOG",
            remote_credentials=False
        )
        Node.objects.get_or_create(
            host="social-distribution-fall2021.herokuapp.com",
            api_prefix="/api",
            username="team04clone",
            password="secret04clone",
            remote_credentials=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_local_auth_credentials),
        migrations.RunPython(add_dev_dummy_auth_credentials),
        migrations.RunPython(add_prod_auth_credentials),
        migrations.RunPython(add_prod_clone_auth_credentials),
    ]
