# Generated by Django 3.2.8 on 2021-11-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211129_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='api_prefix',
            field=models.CharField(blank=True, default='/api', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
